### ISSUE TITLE
[bug] Div by Zero in MicCapture after Unity audio reinit (such as plugging in headphones)

### ISSUE THREAD

**Issue by ckohnert** [Placeholder-Software/Dissonance#33] opened 2017-05-23 17:34 UTC
## Context
When running in OSX (untested in other platforms), if Unity detects a default audio change (such as when plugging in headphones/etc), it reinitializes the audio system causing Dissonance to break.

## Expected Behavior
Microphone re-initializes properly when audio system reconfigures itself.

## Actual Behavior

MicrophoneCapture throws DivByZero repeatedly at the following line due to _clip.samples == 0:

            var samplesToRead = (uint)((_clip.samples + writeHead - _readHead) % _clip.samples);

```
DivideByZeroException: Division by zero
Dissonance.Audio.Capture.MicrophoneCapture.DrainMicSamples () (at Assets/Plugins/Dissonance/Core/Audio/Capture/MicrophoneCapture.cs:180)
Dissonance.Audio.Capture.MicrophoneCapture.Update (Boolean transmit) (at Assets/Plugins/Dissonance/Core/Audio/Capture/MicrophoneCapture.cs:157)
Dissonance.DissonanceComms.Update () (at Assets/Plugins/Dissonance/DissonanceComms.cs:539)
```

## Steps to Reproduce
1. Run the game.
2. Plug in (or remove) a headset (with or without mic) while running.
3. Wait for Unity to reinitialize audio: `Default audio device was changed, but the audio system failed to initialize it (No errors.). Attempting to reset sound system.` Note: Unity audio still functions, despite the somewhat misleading message (i.e. I can still hear sounds, etc).

## Your Environment

- **Dissonance version used**: 1.0.10
- **Unity version**: 5.6.1f1  Personal
- **Editor Operating System and version**: OSX 10.12.5
- **Build Settings**: Dev build and Editor

**Comment by martindevans** [comment] 2017-05-23 23:19
Hi ckohnert,

Unfortunately neither Tom or I can reproduce this on our windows PCs, it could be mac specific or it could be related to audio drivers or even the specific headset you are using. I can well imagine this is an issue though if Unity is invalidating the microphone instance from underneath the capture system all kinds of weirdness could happen!

When this problem happens does the `AudioSettings.OnAudioConfigurationChanged` method run? If so we can use this to catch the event and reset the audio capture system. Try putting this code somewhere in your project startup and seeing what it prints:

```
AudioSettings.OnAudioConfigurationChanged += deviceWasChanged => {
    Debug.LogError("Audio device configuration changed: " + deviceWasChanged);
};
```

**Comment by ckohnert** [comment] 2017-05-24 00:09
Bummer on the repro, I was hoping windows behaved similarly. I've added the line and it does indeed get called (right after the above mentioned "Default audio was changed" message):

      Audio device configuration changed: False

If you guys could hook into that to reset things, that'd be great. I started down the route of trying to detect it by that samples == 0 check but figured you guys would want a proper fix upstream as well.

**Comment by martindevans** [comment] 2017-07-31 23:35
We've just merged a fix for this issue. I'm sorry that took so long - since you already had a fix it's kept getting pushed behind other, higher priority, issues. The fix will be in the next release in a few weeks :)

**Comment by martindevans** [comment] 2017-08-17 21:56
Dissonance 3.0.0 has just released on the Unity asset store, this includes the changes made to resolve this issue so I'll close it now. If the problem persists please feel free to continue posting in this thread. If you're happy with how this issue was handled please consider giving rating and reviewing us on the [asset store](https://www.assetstore.unity3d.com/en/#!/content/70078)!

**Closed by martindevans** 2017-08-17 21:56 UTC
Labels: Status: Awaiting Release, Type: Bug
