### ISSUE TITLE
Voice Activation Trigger Level

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#8] opened 2016-11-09 08:51 UTC
Hello,

I was testing the version 0.0.4 today on LAN using the Voice Activation and the microphone of the Oculus Rift. The Voice Activation works fine the first sentence, then if we wait long enough, a second sentence is fine too. However, if the two sentences are too close from each other in time, then the Voice Activation is not triggered and no data is sent. If we wait a few seconds and start speaking again, the new sentence is sent again. 

I presume the Voice Activation algorithm is waiting for a sharp difference in signal and there need to be a long enough flat signal before it can see the difference and be triggered.

Are you aware of this and would it be possible to tweak the parameter of the algorithm to make it more or less sensitive?

Thanks!

**Comment by TomGillen** [comment] 2016-11-09 15:15
Hi citron4000,

Thanks for the report. We can't reproduce this at the moment, but we will add additional diagnostic options to try and help track this down in the next release. We will also include a sensitivity slider option for voice activation as requested. We should be able to get another release our to you in a few days.

**Comment by martindevans** [comment] 2016-11-11 15:54
Hi citron4000,

I've just pushed out test version 0.0.5 which includes a few things which may help to solve this issue.

## Debugging

There is a new behaviour called `VadDebugUi`. Add this to the same game object as your DissonanceComms behaviour. It will show an overlay like this:

![](https://dissonance.readthedocs.io/en/latest/images/VadDebugUI.png)

This exposes all the internal state of the VAD (unfortunately this is kind of cryptic). Try speaking a little and seeing if any of the parameters go suspiciously large or small when the VAD is misbehaving. **If you can reliably reproduce the VAD misbehaving could you capture a screen recording (with sound!) of this debugging UI and share it with me.**

## Tweaking

From the debug UI you can tweak the VAD sensitivity. You can either use basic configuration, in which case you just have a sensitivity slider, or you can use advanced configuration in which case you have 4 sliders (hover over the text and read [this documentation](https://dissonance.readthedocs.io/en/latest/Reference/Audio/VAD/) for more information on those parameters. I recommend sticking to basic configuration!

Please note these parameters are *not* persisted. So if you tweak the VAD to some perfect level make sure to note your settings. We'll probably add persistence in the next version.

## Recording

Finally there's an option to record various stages of the Dissonance pipeline to file in `DissonanceComms > Diagnostic Settings`. If you record all the recording parts of the pipeline this will capture before and after VAD. A screen recording is probably more helpful though.

# VAD Algorithm

A quick note on how the VAD works which may help you when debugging. For the first ~5 seconds the VAD will *never* detect speech, during this period it is analysing the microphone signal to determine background noise etc. For the first couple of sentences you speak it can be a little picky (it's analysing your speech vs your background noise to tweak it's own settings). It *should* settle down into a reliable detector fairly quickly. **Is your problem just in this startup period, or does it persist no matter how long your leave the VAD in use for?**

**Comment by citron4000** [comment] 2016-11-11 16:00
Many thanks for the update and explanations! I will be testing this on Sunday and let you know how it works and what I find out.

**Comment by citron4000** [comment] 2016-11-14 11:53
I am still testing this and will get back to you on this as soon as possible.

**Comment by citron4000** [comment] 2016-11-15 10:53
I tested with the mp3 of a podcast playing very close to the mic of the Rift. It mostly works fine. But there are also some time where the VAD doesn't pick up the LongSpeech well, as you can see in the video below. In this recording, I let the VAD algorithm run for about a minute.

https://www.dropbox.com/s/b6vtt0ictnmb32y/UnityDissonance-0-0-5-VADTesting.mp4?dl=0

For the time being we will switch to OpenMic (although it has been removed) because the Rift seems to be doing an okay job with it and it doesn't record too much of the environment.

Hope this helps.

**Comment by martindevans** [comment] 2016-11-15 14:53
That's interesting, the numbers in your video are very different (much larger) to e.g. my example image above. This makes sense - I'm testing with a desktop mic positioned behind my monitor (50cm+ away from my mouth) wheras you're using the oculus mic which is obviously pretty close to your mouth!

Would you mind simply recording some oculus microphone input to file and sending me that? To do this go to `DissonanceComms behaviour > Diagnostic Settings > enable "Recording Diagnostics" and "Record Microphone"`. This will record a wav file into a folder called Dissonance_Diagnostics in the working directory. With this sample sound I can fiddle with the settings and auto adaptation without constantly bothering you to try things on the actual hardware :)

**Comment by citron4000** [comment] 2016-11-16 05:28
Thanks! I have uploaded a sample here recording with the Rift's mic [here](https://www.dropbox.com/s/h9slm5axmoqo3so/MicrophoneRawAudio_131237470620400536.wav?dl=0).

**Comment by martindevans** [comment] 2016-11-16 15:40
Thanks very much. I apologise in advance for progress on this issue being a little slow, I'm working on the spatializer/playback bug before I tackle this.

**Comment by citron4000** [comment] 2016-11-20 06:54
Thanks for looking into it :) 

By the way, would it be possible to add OpenMic as well in the next release? In practice, it works quite well with the Rift,

**Comment by martindevans** [comment] 2016-11-20 14:53
I *could* add open mic, it's trivial to do. However I'm resistant to that because VAD should be functionally equivalent to Open mic but be a far better experience for listeners. Obviously this isn't true at the moment and if that remains the case for much longer I will reintroduce Open mic :)

In the meantime if you're fed up with testing the VAD a temporary fix would be to force broadcast triggers permanently on:

```
VoiceBroadcastTrigger a;
a.StartSpeaking();
a.StopSpeaking();
```

Which is basically equivalent to open mic :)

**Comment by citron4000** [comment] 2016-11-22 11:37
Thanks for the answer and for the Channel solution, works great!

**Comment by martindevans** [comment] 2017-04-10 15:05
Finally an update to this issue!

We've never been completely happy with the VAD and we've been doing a lot of work to replace it over the last couple of months. The current test version (I'll email it out to the testers within the hour and it should be live on the store in about a week) includes a completely new VAD based on the excellent chromium WebRTC VAD.

**Comment by citron4000** [comment] 2017-04-10 17:07
That's great, thanks for the hard work and looking forward to try it out!

**Comment by martindevans** [comment] 2017-04-13 13:10
This is now live on the store so I'll *finally* close this issue❗️

**Closed by martindevans** 2017-04-13 13:10 UTC
Labels: Priority: High, Status: Awaiting Release, Type: Bug
