### ISSUE TITLE
[bug] DissonanceComms Access Tokens dropdown immediately closes

### ISSUE THREAD

**Issue by Alexees** [Placeholder-Software/Dissonance#179] opened 2020-02-25 11:20 UTC
## Context
Selecting the DissonanceSetup prefab and opening the Access Tokens Dropdown on the DissonanceComms component immediately closes it again.

## Expected Behavior
stays open

## Actual Behavior
closes immediately

## Workaround
edit mode

## Your Environment

- **Dissonance version used**: 6.4.4

- **Unity version**: e.g. 2018.4.15f1

**Comment by martindevans** [comment] 2020-02-25 15:22
Thanks for reporting this. It seems to be caused by a change in how Unity manages the lifetime of inspectors which means ephemeral state (e.g. foldout state) can no longer be stored in the inspector itself.

I'm working on a full fix for this right now. Until that's released a workaround is to comment out this block in `Assets\Plugins\Dissonance\Editor\TokenControl.cs`:

```
if (_foldout)
{
    _showAccessTokens = EditorGUILayout.Foldout(_showAccessTokens, "Access Tokens");
    if (!_showAccessTokens)
        return;
}
```

This will cause the access token section to always be expanded.

**Comment by martindevans** [comment] 2020-02-25 16:10
This change appears to only affect Prefabs. So another workaround for similar issues is to add the prefab to a scene, change it, apply the changes to the prefab and delete it from the scene.

**Comment by martindevans** [comment] 2020-03-02 16:00
Dissonance 6.4.5 is now on the asset store, it should fix this issue.

**Closed by martindevans** 2020-03-02 16:00 UTC
Labels: Status: Awaiting Release, Type: Bug
