### ISSUE TITLE
OpusException InvalidPacket Exception

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#13] opened 2016-11-22 11:49 UTC
Hello,

Dissonance 0.0.6 works well but we are seeing some Exception popping up during a session. It doesn't seem to affect the voice being transmitted though.

Thanks in advance!

```
[Dissonance:Playback] SpeechSessionStream: Publishing audio session (6 items in buffer)
Dissonance.Log:Info(String, Int32) (at \Unity\Assets\Plugins\Dissonance\Core\Log.cs:264)
Dissonance.Audio.Playback.SpeechSessionStream:Update() (at \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\SpeechSessionStream.cs:91)
Dissonance.Audio.Playback.VoicePlayback:Update() (at \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\VoicePlayback.cs:75)
 
(Filename: /Assets/Plugins/Dissonance/Core/Log.cs Line: 126)

OpusException: Error: Decoding failed: InvalidPacket. '+rh9iIY='! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: EF4BC24C-491E-45D9-974C-FE5CB61BD54E
  at Dissonance.Audio.Codecs.Opus.OpusNative+OpusDecoder.DecodeFloats (Nullable`1 srcEncodedBuffer, ArraySegment`1 dstBuffer) [0x0013a] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Codecs\Opus\Opus.cs:484 
  at Dissonance.Audio.Codecs.Opus.OpusDecoder.Decode (Nullable`1 input, ArraySegment`1 output) [0x00000] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Codecs\Opus\OpusDecoder.cs:39 
  at Dissonance.Audio.Playback.BufferedDecoder.Read (ArraySegment`1 frame) [0x00038] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\BufferedDecoder.cs:66 
  at Dissonance.Audio.Playback.VolumeRampedFrameSource.Read (ArraySegment`1 frame) [0x00000] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\VolumeRampedFrameSource.cs:42 
  at Dissonance.Audio.Playback.FrameToSampleConverter.Read (ArraySegment`1 samples) [0x00142] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\FrameToSampleConverter.cs:84 
  at Assets.Dissonance.Core.Audio.Playback.SoftClipSampleSource.Read (ArraySegment`1 samples) [0x00000] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\SoftClipSampleSource.cs:34 
  at Dissonance.Audio.Playback.Resampler.Read (ArraySegment`1 samples) [0x00026] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\Resampler.cs:41 
  at Dissonance.Audio.Playback.DecoderPipeline.Read (ArraySegment`1 samples) [0x00006] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\DecoderPipeline.cs:63 
  at Dissonance.Audio.Playback.SpeechSession.Read (ArraySegment`1 samples) [0x00000] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\SpeechSession.cs:52 
  at Dissonance.Audio.Playback.SamplePlaybackComponent.Filter (SpeechSession session, System.Single[] data, Int32 channels, System.Single[] temp, Dissonance.Audio.AudioFileWriter diagnosticOutput) [0x00006] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\SamplePlaybackComponent.cs:87 
  at Dissonance.Audio.Playback.SamplePlaybackComponent.OnAudioFilterRead (System.Single[] data, Int32 channels) [0x00021] in \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\SamplePlaybackComponent.cs:69 
 
(Filename: /Assets/Plugins/Dissonance/Core/Audio/Codecs/Opus/Opus.cs Line: 484)

[Dissonance:Playback] SpeechSessionStream: Creating new speech session with buffer time of 100ms
Dissonance.Log:Info(String, Double) (at \Unity\Assets\Plugins\Dissonance\Core\Log.cs:264)
Dissonance.Audio.Playback.SpeechSessionStream:StartSession(FrameFormat, TimeSpan) (at \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\SpeechSessionStream.cs:54)
Dissonance.Audio.Playback.VoicePlayback:StartPlayback() (at \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\VoicePlayback.cs:118)
Dissonance.DissonanceComms:Net_PlayerStartedSpeaking(String) (at \Unity\Assets\Plugins\Dissonance\DissonanceComms.cs:289)
Dissonance.Networking.BaseCommsNetwork`3:OnPlayerStartedSpeaking(String) (at \Unity\Assets\Plugins\Dissonance\Core\Networking\BaseCommsNetwork.cs:289)
Dissonance.Networking.BaseClient`3:InvokeEvent(String&, Action`1) (at \Unity\Assets\Plugins\Dissonance\Core\Networking\BaseClient.cs:273)
Dissonance.Networking.BaseClient`3:DispatchEvents() (at \Unity\Assets\Plugins\Dissonance\Core\Networking\BaseClient.cs:250)
Dissonance.Networking.BaseClient`3:Update() (at \Unity\Assets\Plugins\Dissonance\Core\Networking\BaseClient.cs:222)
Dissonance.Networking.BaseCommsNetwork`3:Update() (at \Unity\Assets\Plugins\Dissonance\Core\Networking\BaseCommsNetwork.cs:143)
Dissonance.Integrations.UNet_HLAPI.HlapiCommsNetwork:Update() (at \Unity\Assets\ThirdParty\Dissonance\Integrations\UNet_HLAPI\HlapiCommsNetwork.cs:32)
 
(Filename: /Assets/Plugins/Dissonance/Core/Log.cs Line: 126)

[Dissonance:Playback] SpeechSessionStream: Publishing audio session (14 items in buffer)
Dissonance.Log:Info(String, Int32) (at \Unity\Assets\Plugins\Dissonance\Core\Log.cs:264)
Dissonance.Audio.Playback.SpeechSessionStream:Update() (at \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\SpeechSessionStream.cs:91)
Dissonance.Audio.Playback.VoicePlayback:Update() (at \Unity\Assets\Plugins\Dissonance\Core\Audio\Playback\VoicePlayback.cs:75)
 
(Filename: /Assets/Plugins/Dissonance/Core/Log.cs Line: 126)
```

**Comment by martindevans** [comment] 2016-11-22 15:52
Hi Citron

This is actually one we've been tracking on our internal bug tracker for a while. It's so far proved to be impossible to reliably reproduce it - so if you notice a pattern to when these happen or encounter a reliable way to reproduce please tell us!

In the meantime please continue to post the same error message in this thread if you encounter it again. The blob in the middle of the message (e.g. '+rh9iIY=') varies each time and may contain useful information.

**Comment by citron4000** [comment] 2016-11-23 07:59
Hi Martin,

Thanks, I'll keep you updated if I find anything.

**Comment by martindevans** [comment] 2016-11-26 03:35
This should be fixed in the next version. However since I never had a 100% reliable way to reproduce this bug I can't be certain! I'll close this issue in a week or so if no one comments here that the issue is still happening.

**Closed** 2016-12-05 00:43 UTC
Labels: Status: Work In Progress, Type: Bug
