### ISSUE TITLE
Possible Start race during LLAPI setup.

### ISSUE THREAD

**Issue by erobledo** [Placeholder-Software/Dissonance#32] opened 2017-05-20 15:23 UTC
## Context

The LLAPI quick start document is not specific about when to perform the  calls to the InitializeAsServer and InitializeAsClient methods in the UNetCommsNetwork.

My first idea was to do so in the Start() method of a manager script. But when I run my program, the network connection was never made. This is probably just a "bug" in the documentation, but I could not find a clean way to fix the issue. I suspect that the problem is that my Start() method gets called before the DissonanceComms Start method.

## Workaround

I have added a IsStarted read property in the DissonanceComms class, that simply returns the value of the _started field. In my manager script, I wait until IsStarted returns true before I call InitializeAsServer or InitializeAsClient. Doing so fixed the issue, and I finally saw the connection message:

[Dissonance:Core] DissonanceComms: Connected to voice comm network

If there is a better way to avoid the problem, I think it should be mentioned in the quick start document. If there is no better method, then the IsStarted method, or an equivalent event, should be added to DissonanceComms.

## Steps to Reproduce

I seem to remember that I also found this problem in the LLAPI Demo scene, simply by moving the _net.InitializeAsClient(_serverIp); call to the Start() method.

## Your Environment

- **Dissonance version used**: v1.0.10
- **Unity version**: e.g. 5.5.1f1 Pro

**Comment by martindevans** [comment] 2017-05-20 23:37
The intention of this API is that it shouldn't matter when those methods get called - they just set some flags which control what the networking system does when it gets around to being initialised. Unfortunately it looks like the initialisation logic is too eager and acts on these flags *before* it has fully initialised itself! For any other network integration this isn't a problem - they've already set up into a session before Dissonance ever starts. The LLAPI is different because it creates it's own session. So the creation logic for servers/clients is trying to run before the network session is created. I'll look into a proper fix for this now.

Your workaround looks like it should successfully solve this issue until a proper fix is released :)

**Comment by martindevans** [comment] 2017-05-21 01:14
Hi again erobledo,

I did some more work on this issue and I've just pushed up a potential fix. I say potential because unfortunately I've been unable to recreate the issue. If you'd like to have a test copy of Dissonance with this patch included please email me your order number for Dissonance (martin@placeholder-software.co.uk). I'd appreciate the the testing to know if the issue is really fixed :)

**Comment by martindevans** [comment] 2017-05-23 13:08
This was automatically closed when we merged the fix for this into our internal master branch. Oops.

Now that's it's merged I can send you the test version I promised :)

**Comment by martindevans** [comment] 2017-06-14 19:25
1.1.0 is now live with these changes so I'll close this issue. Please don't hesitate to re-open the issue if it is still a problem :)

**Closed by martindevans** 2017-06-14 19:25 UTC
Labels: Priority: High, Status: Awaiting Release, Type: Bug
