### ISSUE TITLE
UnityEngine.UnityException: get_deviceType can only be called from the main thread

### ISSUE THREAD

**Issue by WikkidEdd** [Placeholder-Software/Dissonance#73] opened 2018-01-24 20:27 UTC
## Context
When building and running a UWP app there is a unity exception due to SystemInfo.deviceType being outside the main thread.

 BasePreprocessingPipeline: Error: Unhandled exception killed audio preprocessor thread: UnityEngine.UnityException: get_deviceType can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
   at UnityEngineProxy.InternalCalls.SystemInfo_Get_Custom_PropDeviceType()
   at Dissonance.Audio.Capture.WebRtcPreprocessingPipeline.WebRtcPreprocessor.CreatePreprocessor()
   at Dissonance.Audio.Capture.WebRtcPreprocessingPipeline.WebRtcPreprocessor.Reset()
   at Dissonance.Audio.Capture.WebRtcPreprocessingPipeline.ApplyReset()
   at Dissonance.Audio.Capture.BasePreprocessingPipeline.ThreadEntry()

This is being called from IsMobilePlatform()
return SystemInfo.deviceType == DeviceType.Handheld;
 
## Workaround
You can work around this by returning true or false depending on your target platform. This is fine for a temporary workaround, but I'm not really sure of the implications of what the plugin will do if it thinks my device is a mobile platform or not. I'm running on Hololens at the moment, but also occurs in a standard UWP app.

## Steps to Reproduce
1. Import main plugin. 
2. Import HLAPI integration
3. Switch platform to windows store
4. Build
5. Run on local machine in Visual Studio
6. Start Host
7. Observe error in console

## Your Environment

- **Dissonance version used**: 6.0.0
- **Unity version**: 2017.1.1f1
- **Editor Operating System and version**: Windows 10 Home v10.0.16299 Build 16299
- **Build Settings**: Windows Store Application

**Comment by martindevans** [comment] 2018-01-24 22:15
Hi WikkidEdd,

Sorry about that. I actually can't reproduce this on UWP with Unity 5.6, so it must be a platform specific restriction on that API just for some versions of UWP/Unity!

You're absolutely correct about the workaround - add in a bit of specific code for your platform before the offending code:

```

```

Check out the list of defines [here](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html).

For the next release I'll replace the contents of this method entirely will a set of conditional compilation statements so this will never happen again.

**Comment by martindevans** [comment] 2018-01-24 22:22
Sorry I forgot to address this:

> I'm not really sure of the implications of what the plugin will do if it thinks my device is a mobile platform or not

If you're not using [echo cancellation](https://dissonance.readthedocs.io/en/latest/Tutorials/Acoustic-Echo-Cancellation/) it makes absolutely no difference. Dissonance has two independent echo cancellation algorithms, one heavyweight but high quality one designed for powerful platforms (e.g. desktop PC) and one very light but fairly low quality one which can run on phones. So at worst you'll get a much lower quality of AEC if this is wrong.

**Comment by WikkidEdd** [comment] 2018-01-28 13:00
Great, thanks for the feedback!

**Comment by martindevans** [comment] 2018-01-31 14:48
Hi WikkidEdd, Dissonance 6.0.2 went live on the asset store last night which include this fix. I'll close this issue now, feel free to re-open it if there is still something wrong :)

**Closed by martindevans** 2018-01-31 14:48 UTC
Labels: Status: Awaiting Release, Type: Bug
