### ISSUE TITLE
NullReferenceException in HlapiClient:95 when client starts

### ISSUE THREAD

**Issue by TobiasWehrum** [Placeholder-Software/Dissonance#50] opened 2017-08-30 12:30 UTC
## Context
A NullReferenceException gets thrown exactly once on a client when we start our app - maybe before the client is connected. It originates from HlapiClient.cs:95 because "connection" is null.

```
private bool Send(ArraySegment<byte> packet, byte channel)
        {
            if (_network.PreprocessPacketToServer(packet))
                return true;

            var length = _network.CopyPacketToNetworkWriter(packet, _sendWriter);

            // the next line is line 95
            if (!NetworkManager.singleton.client.connection.SendBytes(_sendWriter.AsArray(), length, channel))
            {
                return false;
            }

            return true;
        }
```

## Expected Behavior
No exceptions or errors thrown on startup.

## Actual Behavior
A NullReferenceException when the client tries to use connection before it is available (probably before it is connected?).

## Your Environment
- **Dissonance version used**: 3.0.0
- **Unity version**: 5.6.0f3 (64 bit)
- **Editor Operating System and version**: Windows 7
- **Build Settings**: Tested only in Editor

**Comment by martindevans** [comment] 2017-08-30 13:25
Hi Tobias,

I suspect this is a duplicate of the same fundamental issue in #48. Could you try the workaround I mention [here](https://github.com/Placeholder-Software/Dissonance/issues/48#issuecomment-325754089)?

**Comment by TobiasWehrum** [comment] 2017-08-30 15:03
Hi Martin, works! Will this be in the next version of Dissonance?

**Comment by martindevans** [comment] 2017-08-30 15:04
Yep, assuming Gabe doesn't have any problems with it and it passes code review it should be in the next version of Dissonance :)

**Comment by TobiasWehrum** [comment] 2017-08-30 15:26
Fingers crossed for that. Thanks!

**Comment by martindevans** [comment] 2017-08-31 14:20
Hi Tobias,

Since this is a duplicate of #48 I'll close it now. If you want to get alerts about comments in that thread click the "subscribe" button on the right of the issue.

**Closed by martindevans** 2017-08-31 14:20 UTC
Labels: Close: Duplicate, Type: Bug
