### ISSUE TITLE
[feature] Change microphone during call

### ISSUE THREAD

**Issue by haydenjameslee** [Placeholder-Software/Dissonance#45] opened 2017-08-01 07:27 UTC
1. Is it possible to change the Microphone during a call?

2. If not, how would I implement this myself?

3. Could this be supported as a Dissonance feature in the future?

**Comment by martindevans** [comment] 2017-08-01 12:51
Hi haydenjamesless,

Currently it's not possible to change the mic once Dissonance has started up. The closest you can get is setting the `DissonanceComms:MicrophoneName` property *before* Dissonance is enabled.

Coincidentally I was working on something related to this yesterday and hopefully this will be available in the next version. To do this yourself I think the following should work (I should note I haven't tested this yet):

 - Add [these two methods](https://gist.github.com/martindevans/e5aec2a4f70fc177a254886e4de2758a) to DissonanceComms.cs
 - Change the MicrophoneName property in DissonanceComms to look [like this](https://gist.github.com/martindevans/f1c38421496c964eab4ab66209fffa29)

This should cause the capture and encoding pipeline to destroy itself and then recreate itself (using the mic name) every time you change the `MicrophoneName` property.

Hopefully I'll get some time to work on this later today, I'll post another comment in this thread if I discover anything else you need to do :)

**Comment by martindevans** [comment] 2017-08-02 14:30
This feature was just merged into our development branch and will be available in the next version of Dissonance :)

**Comment by haydenjameslee** [comment] 2017-08-02 15:29
Awesome, glad to hear it! Really appreciate the responsiveness!

In case it helps: I tried the code you sent above had one issue. When i change the mic it stops transmitting the audio data. It is still getting the data from the mic because I can see in the Unity inspector window the volume bar reacting to my voice, however I can see by the bandwidth counts in the same inspector window that there data is no longer being transmitted. 

I'm using Photon Server.

In your implementation did you use the exact code above or were there other changes?

**Comment by martindevans** [comment] 2017-08-02 16:02
I've just tested the mic switching on the development branch again (specifically with photon) and it's working fine for me (using the demo scene, both with PTT and VAD activation). My implementation is almost exactly the same as I gave to you (just with a little bit of extra logging code).

I _hope_ this is just an implementation error. Just to be sure do you want a build of the dev branch (I'll appreciate the extra testing)? Send your order number to [martin@placeholder-software.co.uk](mailto://martin@placeholder-software.co.uk) if so.

**Comment by haydenjameslee** [comment] 2017-08-03 06:12
Will do! Do you have a rough estimate for next release?

**Comment by haydenjameslee** [comment] 2017-08-03 08:23
I got it working in a fresh project! Must have screwed up something in the main project.

**Comment by haydenjameslee** [comment] 2017-08-03 09:24
I worked out its working in my main project if I use PTT activation, but not VAD. Any idea what could be going wrong?

**Comment by haydenjameslee** [comment] 2017-08-03 10:13
I narrowed it down to:

It works when I switch microphones and PTT is selected, and then switch to VAD. BUT if I switch while VAD is selected, it doesn't work.

**Comment by martindevans** [comment] 2017-08-03 13:22
> Do you have a rough estimate for next release?

probably 3-4 weeks, we don't have a set schedule for releases though - just when enough features have been implemented that it's worth doing a release.

> It works when I switch microphones and PTT is selected, and then switch to VAD. BUT if I switch while VAD is selected, it doesn't work.

That's interesting, was the VAD *active* (i.e. detecting speech) when you switched?

I'll try to reproduce this now.

**Comment by martindevans** [comment] 2017-08-03 13:42
I can't reproduce this exactly but I did find some strange behaviour which is probably the cause of your problems. If a channel is open at the moment the mic changes playback is disrupted (in my case it broke up very badly). This is because the remote end never realises that there was an interruption in speech and so tries to continue playback - but of course there was an interruption in the stream of packets while the capture system changed microphones so the timing is all wrong. I'll work on fixing this now, in the meantime if you send me your order number I'll send you a build as soon as I have one :)

**Comment by haydenjameslee** [comment] 2017-08-03 14:24
Sent!

**Comment by haydenjameslee** [comment] 2017-08-07 07:10
I tested the dev build and it seems to be working. I need to run some more extensive tests but so far all good.

**Comment by haydenjameslee** [comment] 2017-08-07 15:59
Did some more tests. All working great!

**Comment by martindevans** [comment] 2017-08-07 16:00
Fantastic! Thanks very much for testing that :D

**Comment by martindevans** [comment] 2017-08-17 21:55
Dissonance 3.0.0 has just released on the Unity asset store, this includes the changes made to resolve this issue so I'll close it now. If the problem persists please feel free to continue posting in this thread. If you're happy with how this issue was handled please consider giving rating and reviewing us on the [asset store](https://www.assetstore.unity3d.com/en/#!/content/70078)!

**Closed by martindevans** 2017-08-17 21:55 UTC
Labels: Status: Awaiting Release, Type: Feature Request
