### ISSUE TITLE
Insufficient space in packet writer to write ushort

### ISSUE THREAD

**Issue by GabeBigBoxVR** [Placeholder-Software/Dissonance#100] opened 2018-06-22 02:32 UTC
## Context
DissonanceException: Error: Insufficient space in packet writer to write ushort! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: ED58BC0A-CAD2-4AFB-BFDD-B5AF5BF7DDDB
  at Dissonance.Networking.PacketWriter.Check (Int32 count, System.String type) [0x00000] in <filename unknown>:0
  at Dissonance.Networking.PacketWriter.Write (UInt16 u) [0x00000] in <filename unknown>:0
  at Dissonance.Networking.PacketWriter.WriteHandshakeResponse[HlapiConn] (UInt32 session, UInt16 clientId, System.Collections.Generic.List`1 clients, System.Collections.Generic.Dictionary`2 peersByRoom) [0x00000] in <filename unknown>:0
  at Dissonance.Networking.Server.BroadcastingClientCollection`1[Dissonance.Integrations.UNet_HLAPI.HlapiConn].ProcessHandshakeRequest (HlapiConn source, Dissonance.Networking.PacketReader& reader) [0x00000] in <filename unknown>:0
  at Dissonance.Networking.BaseServer`3[Dissonance.Integrations.UNet_HLAPI.HlapiServer,Dissonance.Integrations.UNet_HLAPI.HlapiClient,Dissonance.Integrations.UNet_HLAPI.HlapiConn].NetworkReceivedPacket (HlapiConn source, ArraySegment`1 data) [0x00000] in <filename unknown>:0
  at Dissonance.Integrations.UNet_HLAPI.HlapiServer.OnMessageReceivedHandler (UnityEngine.Networking.NetworkMessage netmsg) [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkConnection.HandleReader (UnityEngine.Networking.NetworkReader reader, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkConnection.HandleBytes (System.Byte[] buffer, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkConnection.TransportReceive (System.Byte[] bytes, Int32 numBytes, Int32 channelId) [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkServer.OnData (UnityEngine.Networking.NetworkConnection conn, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkServer+ServerSimpleWrapper.OnData (UnityEngine.Networking.NetworkConnection conn, Int32 receivedSize, Int32 channelId) [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkServerSimple.HandleData (Int32 connectionId, Int32 channelId, Int32 receivedSize, Byte error) [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkServerSimple.Update () [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkServer.InternalUpdate () [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkServer.Update () [0x00000] in <filename unknown>:0
  at UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () [0x00000] in <filename unknown>:0

## Expected Behavior
Have space for ushort

## Steps to Reproduce
1.  Running on server with 4 GB of RAM, 

```
top - 02:30:25 up 48 days,  7:59,  2 users,  load average: 1.24, 1.34, 1.29
Tasks: 129 total,   3 running, 126 sleeping,   0 stopped,   0 zombie
%Cpu(s):  63.6/3.0    67[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                                 ]
KiB Mem :  4045076 total,   132464 free,  1701484 used,  2211128 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  2017836 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
10502 root      20   0 2844352 1.524g  39664 R 136.8 39.5  75:38.74 AppServer
```

## Your Environment
_Include as many relevant details about the environment you experienced the bug in_

- **Dissonance version used**: 6.2.2
- **Unity version**: 2018.1.4f1
- **Editor Operating System and version**: Ubuntu 16.04.4 LTS
- **Build Settings**: Linux 64-bit

**Comment by martindevans** [comment] 2018-06-22 08:15
Hi Gabe,

This sounds like a duplicate of #97 - did you have a lot of players in the session (~20+)?

**Comment by gabosgab** [comment] 2018-06-22 14:57
Yes it was, this is a dupe then.

**Comment by martindevans** [comment] 2018-06-23 14:28
I'll close this one then, keep an eye on #97 for progress. I've already written a prototype to fix the problem (in a way which is protocol compatible, so upgrading clients should be painless). That needs a lot of testing but assuming it all goes well I should be able to get a prototype to you early next week :)

**Closed by martindevans** 2018-06-23 14:28 UTC
Labels: Close: Duplicate
