### ISSUE TITLE
Warning that pops up a lot

### ISSUE THREAD

**Issue by morderkaine1** [Placeholder-Software/Dissonance#28] opened 2017-05-05 01:34 UTC
Hi, Just a warning that pops up a lot. Doesn't really appear to affect how it works, though maybe its related to cut outs.

[Dissonance:Playback] Player Playback: Playback desync (26033ms) beyond recoverable threshold; resetting stream to current time
UnityEngine.Debug:LogWarning(Object)
Dissonance.LogMessage:Log() (at Assets/Plugins/Dissonance/Core/Log.cs:91)
Dissonance.Logs:WriteMultithreadedLogs() (at Assets/Plugins/Dissonance/Core/Log.cs:105)
Dissonance.DissonanceComms:Update() (at Assets/Plugins/Dissonance/DissonanceComms.cs:491)

**Comment by martindevans** [comment] 2017-05-05 01:41
Hi morderkaine1,

That's definitely a bug which will be causing your audio to be badly delayed and then eventually some audio will be lost (every time this message pops up). This is essentially the same issue you're seeing in #29 (they're different ways of detecting the same problem in different ways).

We've had a few reports of issues like this but haven't managed to reproduce it yet. Could you give us some more details on your setup please - On your DissonanceComms component click _Diagnostic Settings_ and increase the logging settings:

 - Core: Trace
 - Recording: Debug
 - Network: Trace
 - Playback: Debug

Then send a [complete log](https://docs.unity3d.com/Manual/LogFiles.html) from both the sender and the receiver when this happens.

**Comment by antoniohof** [comment] 2017-06-09 19:15
I'm getting this too using Android and IOS and Photon. The default scene, and with wifi network.
It seems to increase delay up to a point that it's not usable.

**Comment by martindevans** [comment] 2017-06-09 20:24
Hi antoniohof, Could you send me the same log I requested from moderkaine1?

**Comment by antoniohof** [comment] 2017-06-14 18:10
This seems to be a problem on the Skip function on SamplePlaybackComponent class.
It also causes some glitching on the audio until it finally resyncs after passing through function several times. Soon after that it also causes the "EncodedAudioBuffer: Error: Encoded audio heap is getting very large (41 items)! ".

I commented the Skip class, returning true when it was Desynced over 1 sec and false when it is synced and this fixes those errors and the glitch. 
But I don't know whats implications this might has to the stability of the code.

**Comment by martindevans** [comment] 2017-06-14 19:23
I guess you tried that fix using Dissonance 1.0.10? Dissonance 1.1.0 just went live on the store last night and includes some fixes to the `Skip` method (so if it is invoked, it only runs once, previously it skipped the wrong amount and had to skip several times to get back in sync).

However `Skip` should _never happen_ - the whole pipeline should always stay in sync within a few 10s of milliseconds. `Skip` is basically Dissonance giving up, throwing away a load of audio (deliberately causing a horrible audio glitch) all to get back into sync.

So the real question is what is causing the system to get so terribly out of sync in the first place? Could you send me those detailed logs I mentioned above so I can look further into the issue?

**Comment by martindevans** [comment] 2017-07-18 13:09
We've had 2 new versions on the store since this was last reported so I'll close this issue. Please don't hesitate to re-open it if you encounter the errors again.

**Comment by TobiasWehrum** [comment] 2017-08-24 17:30
Hey @martindevans !

We got the "Error: Encoded audio heap is getting very large (74 items)! This is probably a bug in Dissonance, we're sorry!" etc warning in Dissonance 3.0 - and while trying to reproduce it, we discovered that it happens for us when
- client A (in the editor) does something with the editor, e.g. opening the Edit menu
- client B (also in the editor, but no idea if that matters) speaks at the same time.

Client A gets the warning, and even after closing the Edit menu the warning continues to be thrown.

**Comment by martindevans** [comment] 2017-08-24 17:41
Hi Tobias,

We actually have an internal issue tracking this - the problem is that interacting with the editor sometimes causes a small stall and that throws the recording and playback systems out of sync. I'll investigate if we can add some kind of internal checking for this issue (e.g. detecting the desync and resetting everything automatically).

As a temporary workaround does stopping talking, waiting a few seconds, and then resuming speech fix the issue? Essentially performing a complete reset of the playback system by hand.

**Comment by TobiasWehrum** [comment] 2017-08-24 18:01
Yes, your temporary workaround works. The warning will pop up constantly as long as people are talking, and when they stop for a bit it won't return even when they start talking again (unless I trigger it again).

**Comment by martindevans** [comment] 2017-08-25 18:02
I tried to reproduce your problem with this code inserted into inspector:

```
if (GUILayout.Button("Lock Up Editor"))
   Thread.Sleep(1250);
```

That caused some problems, sometimes a warning about heap size popped up but the speech session always continues to work (usually with a slight skip). Is that an accurate reproduction of the problem you have?

I did find a bug in the timing code which was causing the sync system to not properly re-synchronise, I've fixed that and it should be available in the next version of Dissonance :)

**Comment by TobiasWehrum** [comment] 2017-08-26 00:46
I won't be able to check it until next Wednesday, but that sounds mostly like I remember it - except that there are **always** dozens of heap warnings.

If you execute one of the clients in the editor and open one of the editor menues for a few seconds you'll probably get a more accurate reproduction.

**Comment by martindevans** [comment] 2017-08-30 16:18
Hi Tobias just a quick update on this one. As I mentioned before I investigated it and found what I thought was a bug in the sync code, Tom rejected the change because I'd misunderstood some details of the sync system. I'm going to investigate this some more to see if there's something else I can do.

**Comment by martindevans** [comment] 2017-09-05 14:33
Another update on this one. I've been tracking through a lot of complex timing related code in the various synchronisation systems that Dissonance has running and I think this is basically being caused by two problems at once:

 - Capture system desyncs because the mic hardware continues to accumulate samples while the editor is frozen. When the freeze ends all the samples come in at once which causes buffers to overflow. The capture system has buffers to handle a few milliseconds of jitter, but can't sensibly handle multiple seconds of jitter.
 - Playback system deliberately delays playout so that it can fill it's jitter buffer (the slight delay is worth much smoother playback). However, if one speech session is delayed so badly that it overlaps the start of the next session the buffers overfill (not a problem, but it does cause those warnings). There is *also* a bug related to the unexpected delay because we assume the session will start at the right time, because of the overlap this isn't a good assumption and it causes the sync system to detect a fake playback desync as soon as the audio playback starts.

I've just submitted a PR for review with changes which fix both of these things. Hopefully that will be merged soon and I'll be able to send you a test version :)

**Comment by martindevans** [comment] 2017-09-08 16:53
Apologies for not getting you that test version, we merged in the fixes late last night and then went right ahead with the release of 3.0.1 (which is now available on the store).

I'll close it now - If the problem persists please feel free to continue posting in this thread. If you're happy with how this issue was handled please consider rating and reviewing us on the asset store!

**Closed by martindevans** 2017-09-08 16:53 UTC
Labels: Priority: High, Status: Awaiting Release, Type: Bug

**Comment by morderkaine1** [comment] 2017-09-20 03:50
Hi,
I have tried to update to the latest version of Dissonance from a rather
old version using Unity 5.6.3f1 and I have noticed that the setup
documentation for UNET mentions scripts and things that dont seem to exist
anymore?
Also the Dissonance Comms script is complaining in the inspector about a
Comms Network Component being needed?

**Comment by martindevans** [comment] 2017-09-20 14:18
Hi morderkaine,

I've had a brief skim through the current docs and I don't see any problems, could you clarify a few points:
 - Which version of Dissonance did you upgrade from?
 - Which documentation is it that has the problems?
 - Which components are mentioned which do not exist?

> Also the Dissonance Comms script is complaining in the inspector about a Comms Network Component being needed?

This is a sanity check built into Dissonance, it expects a comms network component to be a sibling of the DissonanceComms component - there is usually a DissonanceSetup prefab in the integration folder which sets this up correctly for you.

An unfortunate fact of the Unity asset installer is that it never _removes_ files, only creates or replaces them. Nowadays we never delete files from Dissonance (we leave an empty file in place when we want to delete something) but if you're coming from a sufficiently old version it's possible we weren't doing it back then. I suspect you're seeing some old files which are confusing matters - could you try deleting `Assets/Plugins/Dissonance` and `Assets/Dissonance` and importing Dissonance again?

**Comment by morderkaine1** [comment] 2017-09-21 02:07
Hi,
I was doing things a little wrong and the biggest problem was the pop up
window with the link to the integrations folder stuff was not popping up
and Window ->Dissonance was not appearing either.
I had to start a new project and install Dissonance there in order to get
it to pop up and appear in Window menu. Now it seems to be working.
