### ISSUE TITLE
UNet_HLAPI Demo Scene Error

### ISSUE THREAD

**Issue by citron4000** [Placeholder-Software/Dissonance#3] opened 2016-10-16 07:04 UTC
Hello,

We opened the "DissonanceHlapiDemo" scene in "Integrations/UNet_HLAPI/Demo" folder and the only change we have made is to change the "Voice Broadcast Trigger" -> "Activation Mode" to "Open Mic". 

When we launch the scene and press "H" to start a host, we get the following error:

> NullReferenceException: Object reference not set to an instance of an object
> Dissonance.DissonanceComms.<DissonanceComms>m__15 (System.String id, Boolean _) (at Assets/Dissonance/DissonanceComms.cs:79)
> Dissonance.Channels2[Dissonance.RoomChannel,System.String].OnOpenedChannel (RoomChannel channel) (at Assets/Dissonance/Core/Channels.cs:86)
> Dissonance.Channels2[Dissonance.RoomChannel,System.String].Open (System.String id, Boolean positional) (at Assets/Dissonance/Core/Channels.cs:64)
> Dissonance.VoiceBroadcastTrigger.OpenChannel () (at Assets/Dissonance/VoiceBroadcastTrigger.cs:206)
> Dissonance.VoiceBroadcastTrigger.Update () (at Assets/Dissonance/VoiceBroadcastTrigger.cs:93)

After that, it continues and we get:

> [Dissonance:Network] HlapiClient: Client connected to server
> [Dissonance:Core] Dissonance Comms Component: Connected to voice comm network
> [Dissonance:Recording] Microphone: Began microphone capture

We are on Unity 5.4.1p2 on Windows and building for x86.

**Comment by martindevans** [comment] 2016-10-16 14:08
Hi citron4000, thanks for the bug report.

I think I have identified the cause of the exception: It looks like when that event fires the `_transmissionPipeline` is null - can you confirm this with the debugger? If you're not sure how to do this just attach a debugger, create the issue, and take a screenshot of the "locals" window (Debug > Windows > Locals).

On a deeper level this is a bug with the initialization order. The `_transmissionPipeline` object is created when you get the message

> [Dissonance:Core] Dissonance Comms Component: Connected to voice comm network

which is of course happening *after* something is trying to access the object!

I'll investigate the root cause and get back to you :)

**Comment by citron4000** [comment] 2016-10-16 15:31
Hi Martin,

Thanks for the quick reply. Yes, you are right, I checked in the debugger and the `_transmissionPipeline` variable is null when the exception is raised.

Thanks again for your help.

**Comment by martindevans** [comment] 2016-10-16 17:49
Hi again citron4000. Thanks for confirming that for me :)

I've just pushed up a fix for this which will be in the next testing release which should be released within the next few of days.

In the meantime I suggest using voice activation instead of open mic. We're actually likely to remove the open mic functionality altogether because it *really* sucks to be on the receiving end of someone using open mic!

**Closed by martindevans** 2016-10-16 17:49 UTC
Labels: Priority: High, Status: Work In Progress, Type: Bug
