### ISSUE TITLE
Reconnection Error

### ISSUE THREAD

**Issue by marwie** [Placeholder-Software/Dissonance#30] opened 2017-05-18 08:38 UTC
Hi, 

we've bought your asset a couple of days ago and trying out your HLAPI as well as LLAPI integrations. Unfortunately LLAPI has some issues I'm not sure how to resolve them and that seem unusual.
I'm currently working with Unity 5.6.0f3. Empty Project, Dissonance Package imported as well asLLAPI integration.

## Steps
0) Open DissonanceLlapiDemo
1) Build project, x64, development build
2) run build as client/server
3) run unity editor and connect (2-3 may be flipped)
4) wait a sec, maybe talk
5) disconnect client
6) wait a sec
7) reconnect
sometimes when reconnecting/disconnecting something goes wrong and the following errors appear. After that I'm not able to connect to the server anymore and have to restart the server.

Server side error:
```
host id {0} has been already deleted
UnityEngine.Networking.NetworkTransport:ReceiveFromHost(Int32, Int32&, Int32&, Byte[], Int32, Int32&, Byte&)
Dissonance.Integrations.UNet_LLAPI.UNetServer:ReadMessages() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:47)
Dissonance.Networking.BaseServer`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:78)
Dissonance.Networking.BaseCommsNetwork`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:124)

[Dissonance:Network] UNetServer: Error reading server socket: WrongHost
UnityEngine.Debug:LogError(Object)
Dissonance.Logs:SendLogMessage(String, Action`1) (at Assets/Plugins/Dissonance/Core/Log.cs:114)
Dissonance.Log:WriteLog(LogLevel, String) (at Assets/Plugins/Dissonance/Core/Log.cs:167)
Dissonance.Log:WriteLogFormat(LogLevel, String, NetworkError) (at Assets/Plugins/Dissonance/Core/Log.cs:190)
Dissonance.Log:Error(String, NetworkError) (at Assets/Plugins/Dissonance/Core/Log.cs:340)
Dissonance.Integrations.UNet_LLAPI.UNetServer:ReadMessages() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:50)
Dissonance.Networking.BaseServer`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:78)
Dissonance.Networking.BaseCommsNetwork`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:124)
```

Client-side error
```
[Dissonance:Network] UNetClient: Failed to cleanly disconnect from Dissonance server at 127.0.0.1:5889, Error WrongConnection
UnityEngine.Debug:LogError(Object)
Dissonance.Logs:SendLogMessage(String, Action`1) (at Assets/Plugins/Dissonance/Core/Log.cs:114)
Dissonance.Log:WriteLog(LogLevel, String) (at Assets/Plugins/Dissonance/Core/Log.cs:167)
Dissonance.Log:WriteLogFormat(LogLevel, String, String, UInt16, NetworkError) (at Assets/Plugins/Dissonance/Core/Log.cs:208)
Dissonance.Log:Error(String, String, UInt16, NetworkError) (at Assets/Plugins/Dissonance/Core/Log.cs:352)
Dissonance.Integrations.UNet_LLAPI.UNetClient:Disconnect() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetClient.cs:40)
Dissonance.Networking.BaseCommsNetwork`3:StopClient() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:186)
Dissonance.Integrations.UNet_LLAPI.Demo.LlapiManager:OnGUI() (at Assets/Dissonance/Integrations/UNet_LLAPI/Demo/LlapiManager.cs:45)
```

When restarting the server (full restart, close application, reopening the application) and do not stop the client and try to reconnect I get:

```
[Dissonance:Network] UNetClient: Exception invoking event handler: System.ArgumentNullException: Argument cannot be null.
Parameter name: key
  at System.Collections.Generic.Dictionary`2[System.String,Dissonance.VoicePlayerState].TryGetValue (System.String key, Dissonance.VoicePlayerState& value) [0x000ba] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:608 
  at Dissonance.DissonanceComms.Net_PlayerStartedSpeaking (System.String player) [0x0000a] in D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\DissonanceComms.cs:417 
  at Dissonance.Networking.BaseCommsNetwork`3[Dissonance.Integrations.UNet_LLAPI.UNetServer,Dissonance.Integrations.UNet_LLAPI.UNetClient,System.Int32].OnPlayerStartedSpeaking (System.String obj) [0x00010] in D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Networking\BaseCommsNetwork.cs:296 
  at Dissonance.Networking.BaseClient`3[Dissonance.Integrations.UNet_LLAPI.UNetServer,Dissonance.Integrations.UNet_LLAPI.UNetClient,System.Int32].InvokeEvent[String] (System.String& arg, System.Action`1 handler) [0x0000f] in D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Networking\BaseClient.cs:316 
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Dissonance.Logs:SendLogMessage(String, Action`1) (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Log.cs:114)
Dissonance.Log:WriteLog(LogLevel, String) (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Log.cs:167)
Dissonance.Log:WriteLogFormat(LogLevel, String, Exception) (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Log.cs:190)
Dissonance.Log:Error(String, Exception) (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Log.cs:340)
Dissonance.Networking.BaseClient`3:InvokeEvent(String&, Action`1) (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Networking\BaseClient.cs:320)
Dissonance.Networking.BaseClient`3:DispatchEvents() (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Networking\BaseClient.cs:282)
Dissonance.Networking.BaseClient`3:Update() (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Networking\BaseClient.cs:174)
Dissonance.Networking.BaseCommsNetwork`3:Update() (at D:\Tests\AudioPluginTest\Assets\Plugins\Dissonance\Core\Networking\BaseCommsNetwork.cs:128)
```

The dicionary error may be resolved by just adding a check if state already exists for this key and if so just update/replace the state.I already tried that but it doesn't resolve the initial error.

Can you reproduce the error? If not I can upload you my test project. Or if you need anything else let me know.

Would be great if you could give a quick hint if this is a known issue and/or being worked on or not so that I can plan ahead.

Best
Marcel

**Comment by marwie** [comment] 2017-05-18 08:54
Here is some additional testing:

I tried adding 

```
            if (PlayerLeft != null)
                PlayerLeft.Invoke(_playerName);
```
to BaseClient.cs at the end of "Disconnect()" (in a different project), because was wondering why the list of connected Players didnt update on the client side and only on the server side. 
Together with the Dictionary Key issue worked around I can disconnect/reconnect sometimes quite often, but sometimes (without any apparent reason) I get the "could not disconnect cleanly" error.

---

I tried restarting the server once the client disconnects (just as a test and as the current usecase does only have one client anyways), but this leads to the following warning:

```
[Dissonance:Network] CommsProcessor: Not received ID from Dissonance server; skipping voice packet transmission
UnityEngine.Debug:LogWarning(Object)
Dissonance.LogMessage:Log() (at Assets/Plugins/Dissonance/Core/Log.cs:91)
Dissonance.Logs:WriteMultithreadedLogs() (at Assets/Plugins/Dissonance/Core/Log.cs:105)
Dissonance.DissonanceComms:Update() (at Assets/Plugins/Dissonance/DissonanceComms.cs:564)
```
followed by these errors:
```
maximum hosts cannot exceed {16}
UnityEngine.Networking.NetworkTransport:AddHost(HostTopology, Int32)
Dissonance.Integrations.UNet_LLAPI.UNetServer:Connect() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:25)
Dissonance.Integrations.UNet_LLAPI.UNetServer:ReadMessages() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:53)
Dissonance.Networking.BaseServer`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:78)
Dissonance.Networking.BaseCommsNetwork`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:124)

DissonanceException: Failed to create Dissonance server on port '5889', (port may already be in use)
Dissonance.Integrations.UNet_LLAPI.UNetServer.Connect () (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:27)
Dissonance.Integrations.UNet_LLAPI.UNetServer.ReadMessages () (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:53)
Dissonance.Networking.BaseServer`3[Dissonance.Integrations.UNet_LLAPI.UNetServer,Dissonance.Integrations.UNet_LLAPI.UNetClient,System.Int32].Update () (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:78)
Dissonance.Networking.BaseCommsNetwork`3[Dissonance.Integrations.UNet_LLAPI.UNetServer,Dissonance.Integrations.UNet_LLAPI.UNetClient,System.Int32].Update () (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:124)

host id out of bound id {-1} max id should be greater 0 and less than {16}
UnityEngine.Networking.NetworkTransport:Disconnect(Int32, Int32, Byte&)
Dissonance.Integrations.UNet_LLAPI.UNetClient:Disconnect() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetClient.cs:42)
Dissonance.Networking.BaseCommsNetwork`3:StopClient() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:191)
Dissonance.Integrations.UNet_LLAPI.UNetCommsNetwork:StopClient() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetCommsNetwork.cs:122)
Dissonance.Networking.BaseCommsNetwork`3:StopServer() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:203)
VoipInterfacer:StopServer() (at Assets/Dissonance/Integrations/UNet_LLAPI/Telekom/VoipInterfacer.cs:56)
VoipTest:OnGUI() (at Assets/Dissonance/Integrations/UNet_LLAPI/Telekom/Test/VoipTest.cs:30)

host id {-1} out of bound or host has been already removed
UnityEngine.Networking.NetworkTransport:RemoveHost(Int32)
Dissonance.Integrations.UNet_LLAPI.UNetServer:Disconnect() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:33)
Dissonance.Networking.BaseCommsNetwork`3:StopServer() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:205)
VoipInterfacer:StopServer() (at Assets/Dissonance/Integrations/UNet_LLAPI/Telekom/VoipInterfacer.cs:56)
VoipTest:OnGUI() (at Assets/Dissonance/Integrations/UNet_LLAPI/Telekom/Test/VoipTest.cs:30)
```

**Comment by TomGillen** [comment] 2017-05-18 15:56
Hi marwie,

That's quite a few errors! It looks like you may be suffering from two issues here,

The first set of issues:

> host id {0} has been already deleted

> [Dissonance:Network] UNetClient: Failed to cleanly disconnect from Dissonance server at 127.0.0.1:5889, Error WrongConnection

> maximum hosts cannot exceed {16}

These ones we're not sure about (and we can't reproduce them). This is something going wrong at the unity LLAPI layer and then bubbling up to break Dissonance (probably caused by us not properly handling an error somewhere). If you could send us a repro project that would be great - either post it here or email it to tom@placeholder-software.co.uk :)

The second set of issues:

> [Dissonance:Network] CommsProcessor: Not received ID from Dissonance server; skipping voice packet transmission

> [Dissonance:Network] UNetClient: Exception invoking event handler: System.ArgumentNullException: Argument cannot be null.

These are both probably caused by misusing the DissonanceComms component (similar to issue [#23](https://github.com/Placeholder-Software/Dissonance/issues/23#issuecomment-291511483)). This component is not meant to live between network sessions, if it does it will get very confused about the state of things. This is completely our fault for documenting this badly and we're working to fix it!

If you completely destroy all the Dissonance components and then recreate them when you create a new network session does this fix some/all of these issues?

**Comment by marwie** [comment] 2017-05-18 16:54
Hi Tom,
here's the build with the fresh project: https://we.tl/xWnFat1omA

Regarding the DissonanceComms component: You mean when the server stops and restarts? 

I'll test recreating the plugin tomorrow and let you know how it went!

**Comment by martindevans** [comment] 2017-05-18 22:26
> Regarding the DissonanceComms component: You mean when the server stops and restarts?

That's correct. You just need to make sure that Dissonance components (all of them, comms, network, broadcast, receiver etc) are not re-used between different sessions. We're aware this isn't a great system, hopefully we'll have better handling for this in the future!

**Comment by marwie** [comment] 2017-05-18 22:38
Oh ok, thanks, also thank you for the quick reply. 
If you have time looking into the project and either confirming that you can or can't reproduce the error please let me know.

**Comment by marwie** [comment] 2017-05-19 14:44
Just send an email with the second project attachet to tom@placeholder-software.co.uk

**Comment by TomGillen** [comment] 2017-05-21 07:52
I've been looking through the project you sent me, and have managed to reproduce the some of the problems, although they are extremely intermittent. I'm still trying to diagnose the issue, but it looks like there are a couple of things going wrong here.

So far, it *appears* that what is happening is that for some reason when a client disconnects from the server, there is a small chance that the server's socket is closed (apparently by Unity). Most of the subsequent errors are either direct results of that, or consequences of it down the line. I do not yet know why this is happening, or indeed if this is what is actually happening.

I have also found a few unrelated issues around how disconnects are handled while testing your repro project.

I am still investigating.

**Comment by martindevans** [comment] 2017-05-23 14:41
Hi marwie, just a quick update on progress of this issue.

Tom investigated this over the weekend and logged several bugs into our internal issue tracker. None of them completely explain your issue but they're throwing up their own problems and making it difficult to investigate this issue. I'm working to fix these right now and then we'll get back to investigating what's really going wrong.

**Comment by dibeltran** [comment] 2017-06-01 20:44
Hi Tom and Martin, i'm having the exact same error as marwie! Using LLAPI, when a client disconects from server, server get errors and needs to be restarted! I'm using the demo project that comes with the LLAPI Integration.

**Comment by dibeltran** [comment] 2017-06-01 20:52
marwie, were you initializing dedicated server or just server?

**Comment by marwie** [comment] 2017-06-01 23:43
just server

**Comment by martindevans** [comment] 2017-06-01 23:45
dibeltran are you encountering this with server or dedicated server?

**Comment by dibeltran** [comment] 2017-06-02 00:52
I was using dedicated server. I connected with 3 clients and it was working perfectly. When one of them disconnected, the server crashed with errors.

**Comment by dibeltran** [comment] 2017-06-02 13:42
This is the error

host id {0} has been already deleted
UnityEngine.Networking.NetworkTransport:ReceiveFromHost(Int32, Int32&, Int32&, Byte[], Int32, Int32&, Byte&)
Dissonance.Integrations.UNet_LLAPI.UNetServer:ReadMessages() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:47)
Dissonance.Networking.BaseServer`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:78)
Dissonance.Networking.BaseCommsNetwork`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:124)

**Comment by martindevans** [comment] 2017-06-02 13:45
Does this error happen consistently for you? When Tom initially investigated this issue he found a few things which *might* be related but we can't be sure because he only managed to reproduce it once.

By the way our plan at the moment is to put out a release fairly soon - I'm going to include a load more diagnostics in the LLAPI integration which will hopefully help us track down this issue some more.

**Comment by dibeltran** [comment] 2017-06-02 13:53
If i connect only one client to the server, when it disconnects, everything continue to run smootly! I connected one client and disconnected several times, no problem! If i connect 2 clients, when one of them disconnects, server crashes and start spamming this error, every time!

**Comment by martindevans** [comment] 2017-06-02 13:55
Aha! A reliable reproduction like that will help immensely with fixing this. Thanks dibeltran :+1:

**Comment by dibeltran** [comment] 2017-06-02 14:02
Only one more thing! This is the first error that pops out as soon as the first client leaves

```
Attempt to send to not connected connection {3}
UnityEngine.Networking.NetworkTransport:Send(Int32, Int32, Int32, Byte[], Int32, Byte&)
Dissonance.Integrations.UNet_LLAPI.UNetCommsNetwork:Send(Int32, Int32, Int32, ArraySegment`1, Log) (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetCommsNetwork.cs:116)
Dissonance.Integrations.UNet_LLAPI.UNetServer:Send(Int32, Int32, ArraySegment`1) (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:78)
Dissonance.Integrations.UNet_LLAPI.UNetServer:SendUnreliable(Int32, ArraySegment`1) (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:89)
Dissonance.Networking.BaseServer`3:Dissonance.Networking.Server.IServer<TPeer>.SendUnreliable(Int32, ArraySegment`1) (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:105)
Dissonance.Networking.Server.PacketRouter`1:ProcessVoiceData(Int32, PacketReader&) (at Assets/Plugins/Dissonance/Core/Networking/Server/PacketRouter.cs:49)
Dissonance.Networking.BaseServer`3:NetworkReceivedPacket(Int32, ArraySegment`1) (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:158)
Dissonance.Integrations.UNet_LLAPI.UNetServer:ReadMessages() (at Assets/Dissonance/Integrations/UNet_LLAPI/UNetServer.cs:56)
Dissonance.Networking.BaseServer`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseServer.cs:78)
Dissonance.Networking.BaseCommsNetwork`3:Update() (at Assets/Plugins/Dissonance/Core/Networking/BaseCommsNetwork.cs:124)
```

I'm not sure this is the same thing happening with marwie

**Comment by martindevans** [comment] 2017-06-10 01:09
I've just submitted Dissonance 1.1.0 to the store which I hope should fix this issue. I've tried a lot of variations on creating sessions with multiple players, disconnecting and reconnecting them, using dedicated server or normal servers, disconnecting everything and starting a brand new session without closing any of the windows. Everything seems to work. If you'd like to get a copy of this version before it's available on the store please email martin@placeholder-software.co.uk your order number.

My main work on the networking system was in the following three areas:

## Detecting user errors
The most common problem people have with Dissonance is trying to use the same components between multiple sessions. They can't handle this (yet) and it causes a lot of weird errors. I've added in a lot of checks for all of the top level networking methods to detect if they're called when the network is in the wrong state which should detect this.

## Robust disconnection
Previously the disconnection logic was a bit of a mess. As part of user error detection work I strictly defined the states the network system can be in and made sure that the `disconnecting->disconnected` transition happens properly (i.e. exactly once).

## LLAPI error handling
I also did some work specifically on the LLAPI making sure we handle some corners cases properly.

For example previously if there was an error while reading packets (on the server) we would just bail out of the read method and log the error. Now we specifically check if the error was a fatal error (such as a timeout) and if it was, slam the connection closed and remove the client from the session. This means that if a client connection dies it doesn't stay in the session forever on the server side (and then cause problems when it reconnects).

---

Finally I want to apologise for how long this issue has taken to fix. We already had a large overhaul of networking robustness planned and this fix ended up becoming that, this ended up making the work take a lot more time than a bugfix would have. We try to maintain excellent customer support and if anyone is unsatisfied with how we've handled this I will be happy to offer a refund :)

**Comment by martindevans** [comment] 2017-06-14 19:25
1.1.0 is now live with the fixes for this issue. Please do tell me if this completely fixes the issue for you both :)

**Comment by martindevans** [comment] 2017-07-01 15:22
Since 1.1.0 and 1.1.1 have been out with this fix for a while I'll assume the issue is fixed. Feel free to re-open it if you still have problems.

**Closed by martindevans** 2017-07-01 15:22 UTC
Labels: Priority: High, Status: Awaiting User Feedback, Type: Bug
