### ISSUE TITLE
[bug] PreprocessingPipeline Error

### ISSUE THREAD

**Issue by AVanderstarre** [Placeholder-Software/Dissonance#199] opened 2020-06-12 23:08 UTC
## Context
I followed the quick start guide and the only thing I have changed is changed the name of the global room.  Eventually, when I press the connect/host button on my game, the errors get thrown.  I have re-downloaded and installed the two assets (Dissonance and the Mirror addon), and it seemed to work fine for a bit but then the problem returned.

## Steps to Reproduce
_Provide a detailed set of steps to reproduce the problem_
1.  Use Unity as usual, everything is working
2.  The Dissonance error starts getting thrown suddenly
3.  Restart the Unity Editor
4.  Starts working again for a bit, then the error will begin getting thrown again

![unknown](https://user-images.githubusercontent.com/23583563/84552682-c4f07980-acdf-11ea-9983-493ff17a6304.png)

It seems to be working fine for now.  And as for when the error occurs it currently feels almost random.  Next time I get it I will update this to show more context to the logs.  I will also update if I find a more consistent way to reproduce.

## Your Environment

- **Dissonance version used**:  v7.0.2 (2020-06-03)

- **Unity version**: 2019.3.13f1

- **Editor Operating System and version**: Microsoft Windows 10 Home 10.0.18363 Build 18363

- **Build Settings**:  Happens in editor

**Comment by AVanderstarre** [comment] 2020-06-15 01:21
Here is the full error:
> [Dissonance:Recording] (01:19:06.441) BasePreprocessingPipeline: Error: Unhandled exception killed audio preprocessor thread: Dissonance.DissonanceException: Error: Cannot associate preprocessor with Playback filter - one already exists! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: D5862DD2-B44E-4605-8D1C-29DD2C72A70C
  at Dissonance.Audio.Capture.WebRtcPreprocessingPipeline+WebRtcPreprocessor.SetFilterPreprocessor (System.IntPtr preprocessor) [0x0005e] in A:\Program Files\Unity\Projects\Electromagnetics Project\Electromagnetics Experiment\Assets\Plugins\Dissonance\Core\Audio\Capture\WebRtcPreprocessingPipeline.cs:352 
  at Dissonance.Audio.Capture.WebRtcPreprocessingPipeline+WebRtcPreprocessor.Reset () [0x00061] in A:\Program Files\Unity\Projects\Electromagnetics Project\Electromagnetics Experiment\Assets\Plugins\Dissonance\Core\Audio\Capture\WebRtcPreprocessingPipeline.cs:304 
  at Dissonance.Audio.Capture.WebRtcPreprocessingPipeline.ApplyReset () [0x0000e] in A:\Program Files\Unity\Projects\Electromagnetics Project\Electromagnetics Experiment\Assets\Plugins\Dissonance\Core\Audio\Capture\WebRtcPreprocessingPipeline.cs:55 
  at Dissonance.Audio.Capture.BasePreprocessingPipeline.ThreadEntry () [0x00009] in A:\Program Files\Unity\Projects\Electromagnetics Project\Electromagnetics Experiment\Assets\Plugins\Dissonance\Core\Audio\Capture\BasePreprocessingPipeline.cs:223 ! This is probably a bug in Dissonance, we're sorry! Please report the bug on the issue tracker "https://github.com/Placeholder-Software/Dissonance/issues". You could also seek help on the community at "http://placeholder-software.co.uk/dissonance/community" to get help for a temporary workaround. Error ID: 02EB75C0-1E12-4109-BFD2-64645C14BD5F
UnityEngine.Debug:LogError(Object)
Dissonance.LogMessage:Log() (at Assets/Plugins/Dissonance/Core/Log.cs:67)
Dissonance.Logs:WriteMultithreadedLogs() (at Assets/Plugins/Dissonance/Core/Log.cs:85)
Dissonance.Editor.Windows.Startup:Update() (at Assets/Plugins/Dissonance/Editor/Windows/Startup.cs:33)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by AVanderstarre** [comment] 2020-06-19 15:01
Here are my editor logs with the error, and a screenshot of the errors so you can use the timestamps to find the error in the logs.

[Editor.log](https://github.com/Placeholder-Software/Dissonance/files/4805242/Editor.log)

![image](https://user-images.githubusercontent.com/23583563/85146894-18048800-b21c-11ea-92bd-4dcc6d67ea4c.png)

**Comment by martindevans** [comment] 2020-06-19 15:21
Notes from discussion on Discord related to this bug:
 - Pause on error is enabled.
 - Editor pausing triggered the error in this particular case (but is probably not the root cause).
 - Domain reloading is disabled (this is the default).

**Comment by martindevans** [comment] 2021-01-06 15:57
[Dissonance 7.2.0](https://placeholder-software.co.uk/dissonance/releases/7.2.0.html) was just approved by Unity and is now live on the asset store. That includes a partial fix for this issue. See the full details over on issue [#214](https://github.com/Placeholder-Software/Dissonance/issues/214#issuecomment-755382684).

**Closed by martindevans** 2021-01-06 15:57 UTC
Labels: Status: Work In Progress
