### ISSUE TITLE
[bug] Dissonance Echo Cancellation audio plugin is not showing debug data

### ISSUE THREAD

**Issue by vladbasin** [Placeholder-Software/Dissonance#218] opened 2020-12-28 00:29 UTC
## Context
According to documentation https://dissonance.readthedocs.io/en/latest/Tutorials/Acoustic-Echo-Cancellation/index.html (section 5. Testing AEC), there should be debug information near Dissonance Echo Cancellation audio plugin to understand how well it performs while the app is running.

## Expected Behavior
There should be debug values in Inspector according to documentation
![](https://dissonance.readthedocs.io/en/latest/images/AecStatus.png)

## Actual Behavior
There are NO debug values in Inspector. The configuration is correct.
![image](https://user-images.githubusercontent.com/10499145/103182466-7e99eb00-48bc-11eb-9e9d-0728d46c5e0a.png)

## Your Environment

- **Dissonance version used**: v7.1.5 (2020-12-01)
- **Unity version**: 2020.1.17f1
- **Editor Operating System and version**: MacOS Catalina 10.15.7
- **Build Settings**: Run in Editor

**Comment by martindevans** [comment] 2020-12-28 00:55
This is because a bug in the Unity editor specific to MacOS caused a complete crash of the editor if trying to view this information. I did report the bug to Unity so it's possible that it has been fixed now, you can try removing the preprocessor check in `Assets/Plugins/Dissonance/Editor/DissonanceAecFilterInspector.cs` to see if it has been fixed:

```csharp
#if !(UNITY_EDITOR_OSX && UNITY_2019_3_OR_NEWER) // <--------------- Remove this
float[] data;
if (plugin.GetFloatBuffer("AecMetrics", out data, 10))
{
  // etc
}
#endif // <--------------------------------------------------------- Remove this
```

If that doesn't work I have a workaround that will be in the next version of Dissonance.

**Comment by vladbasin** [comment] 2020-12-28 09:39
@martindevans, after removing these lines, everything works correctly. Looks like this has been fixed. https://issuetracker.unity3d.com/issues/editor-freezes-or-crashes-when-interacting-with-native-audio-plugin-sdks-audio-mixers

However, I can see Fraction Poor Delays is often more than zero. Could you please provide some guide how can I troubleshoot this?

**Comment by martindevans** [comment] 2020-12-28 16:07
> Looks like this has been fixed.

Thanks for confirming that. I've changed it for the next version of Dissonance.

> Fraction Poor Delays is often more than zero.

The AEC system works by correlating output sound (as measured by the filter) to input sound (recorded by the mic), calculating the time delay from playback to recording and then removing echoes. `Fraction Poor Delays` indicates that the timing of the audio stream is too delayed (or too jittery) for the system to work out a proper delay. This is most likely caused by something in your audio system outside of Unity - for example bluetooth headsets often introduce huge latency that prevents the AEC from ever converging.

**Comment by martindevans** [comment] 2021-01-06 15:46
[Dissonance 7.2.0](https://placeholder-software.co.uk/dissonance/releases/7.2.0.html) was just approved by Unity and is now live on the asset store. That includes two fixes for this issue:
 - Since the Unity bug we were working around has been fixed we've changed the inspector so it doesn't show the stats in `MacOS+Unity 2019.3`, all other versions should show the stats.
 - A new script has been added that allows you to fetch the AEC diagnostic data from your own scripts (`Assets/Plugins/Dissonance/Core/Audio/AecDiagnostics.cs`).

**Closed by martindevans** 2021-01-06 15:46 UTC
Labels: Status: Awaiting Release, Type: Support
